version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8  # This can remain the same
    commands:
      - echo Installing dependencies...
      - pip install -r app/requirements.txt

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 992382591393.dkr.ecr.us-east-1.amazonaws.com/my-app

  build:
    commands:
      - echo Running unit tests...
      - python -m unittest discover -s tests -v

      - echo Building Docker image...
      - docker build -t flask-app:latest -f app/Dockerfile .

      - echo Tagging Docker image...
      - docker tag flask-app:latest 992382591393.dkr.ecr.us-east-1.amazonaws.com/my-app:latest

  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push 992382591393.dkr.ecr.us-east-1.amazonaws.com/my-app:latest

