appVersion: v1
kind: Service 
metadata: 
  name: flask-service
spec:
  type: LoadBalancer
  selector: 
    app: flask-microservice
  ports: 
    - protocol: TCP
      port: 80
      targetPort: 5000

